name: fsspec-tutorial
channels:
        - conda-forge
dependencies:
        - python>=3.7
        - fsspec
        - matplotlib
        - numpy
        - s3fs
        - tqdm
        - xarray
        - jupyterlab
        - h5py
        - zarr
