name: fsspec-tutorial
channels:
        - conda-forge
dependencies:
        - python==3.8
        - git
        - pip
        - fsspec
        - matplotlib
        - numpy
        - s3fs
        - tqdm
        - xarray
        - jupyterlab
        - h5py
        - zarr
        - dask
        - pip:
            - numcodecs>=0.8.0
            "--editable=git+https://github.com/intake/fsspec-reference-maker"
